Repository taed2-2425q1-gced-upc/TAED2_YOLOs, pull requests merged in 2024-10, with the labels that each got.

#6 [CHORE] Set up environmental variables
  .env.test
Labels: maintenance

#7 [FEAT] Create data pipeline
  notebooks/0_dataPipelines.ipynb
  notebooks/config.yaml
  person_image_segmentation/utils/processing.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#8 [FEAT] Update data pipeline
  data.dvc
  person_image_segmentation/pipelines/config.yaml
  person_image_segmentation/pipelines/dataPipelines.py
  upload_data_dvc.sh
Labels: enhancement

#4 [CHORE] Initialize MLFlow
  Makefile
  mlruns/0/meta.yaml
  notebooks/1_MlflowExperiments.ipynb
  poetry.lock
  pyproject.toml
Labels: maintenance

#18 [FEAT] Data card
  cards/DatasetCard.md
Labels: documentation

#19 [FEAT] DVC Pipeline
  .env.test
  .gitignore
  data.dvc
  data/interim/splitted.dvc
  data/interim/transformed.dvc
  data/processed.dvc
  data/raw.dvc
  dvc.lock
  dvc.yaml
  person_image_segmentation/pipelines/dataPipelines.py
  person_image_segmentation/pipelines/evaluationPipeline.py
  person_image_segmentation/pipelines/predictionPipeline.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#23 [FIX] Solve data pipeline path issue
  person_image_segmentation/pipelines/dataPipelines.py
Labels: bug

#24 [CHORE] Refactor utils scripts
  person_image_segmentation/utils/run_kaggle_dataset.py
  person_image_segmentation/utils/run_kaggle_model.py
Labels: maintenance

#25 [FEAT] Mlflow evaluation
  metrics/emissions_evaluation.csv
  metrics/scores.json
  person_image_segmentation/modeling/evaluation.py
Labels: enhancement

#26 [CHORE] Model card
  cards/ModelCard.md
Labels: documentation

#27 [FIX] Dvc issues
  .gitignore
  data/interim/splitted.dvc
  data/interim/transformed.dvc
  data/processed.dvc
  data/raw.dvc
  dvc.lock
  dvc.yaml
  models/configs/config_yolos_sample_train.yaml
  person_image_segmentation/modeling/prediction.py
  person_image_segmentation/modeling/simple_train.py
  person_image_segmentation/modeling/train_v0.py
  person_image_segmentation/pipelines/complete_data_folder.py
  person_image_segmentation/pipelines/create_labels.py
  person_image_segmentation/pipelines/download_raw_data.py
  person_image_segmentation/pipelines/split_data.py
  person_image_segmentation/pipelines/transform_masks.py
  person_image_segmentation/utils/dataset_utils.py
Labels: bug

#15 [CHORE] Add instructions to execute project
  README.md
  metrics/powermetrics_log.txt
  notebooks/0_NG_data-pipelines.ipynb
  notebooks/config.yaml
  upload_data_dvc.sh
Labels: documentation

#31 [CHORE] Update README
  README.md
Labels: documentation

#32 [CHORE] Update .env template
  .env.test
Labels: documentation

#36 [FEAT] Api creation
  person_image_segmentation/api/app.py
  person_image_segmentation/api/schema.py
  poetry.lock
  pyproject.toml
  static/favicon.ico
Labels: maintenance

#38 [FEAT] Code testing using PyTest
  .env.test
  .gitignore
  person_image_segmentation/api/app.py
  person_image_segmentation/config.py
  person_image_segmentation/modeling/prediction.py
  person_image_segmentation/pipelines/complete_data_folder.py
  person_image_segmentation/utils/dataset_utils.py
  person_image_segmentation/utils/modeling_utils.py
  pyproject.toml
  tests/test_api.py
  tests/test_data.py
  tests/test_image.jpg
  tests/test_image.png
  tests/test_image_no_mask.png
  tests/test_model.py
Labels: enhancement

#34 [CHORE] Satic analysis
  dvc.lock
  dvc.yaml
  person_image_segmentation/config.py
  person_image_segmentation/modeling/evaluation.py
  person_image_segmentation/modeling/prediction.py
  person_image_segmentation/modeling/train_v0.py
  person_image_segmentation/pipelines/data_pipelines.py
  person_image_segmentation/utils/processing.py
  person_image_segmentation/utils/run_kaggle_dataset.py
  person_image_segmentation/utils/run_kaggle_model.py
  poetry.lock
  pyproject.toml
  tests/test_data.py
  tests/test_model.py
Labels: maintenance

#45 [CHORE] Notebooks refactor
  .gitignore
  notebooks/0_NG_data-pipelines.ipynb
  notebooks/1_MJ_mlflow-experiments.ipynb
  notebooks/2_MR_predictions-&-postprocessing-pipeline.ipynb
  notebooks/3_MR_evaluation.ipynb
  person_image_segmentation/modeling/evaluation.py
  person_image_segmentation/utils/modeling_utils.py
Labels: maintenance

#46 [CHORE] Static analysis for maintenance
  person_image_segmentation/api/app.py
  person_image_segmentation/api/schema.py
  person_image_segmentation/config.py
  person_image_segmentation/modeling/evaluation.py
  person_image_segmentation/modeling/simple_train.py
  person_image_segmentation/modeling/train_v0.py
  person_image_segmentation/pipelines/complete_data_folder.py
  person_image_segmentation/pipelines/create_labels.py
  person_image_segmentation/pipelines/download_raw_data.py
  person_image_segmentation/pipelines/split_data.py
  person_image_segmentation/pipelines/transform_masks.py
  person_image_segmentation/utils/api_utils.py
  person_image_segmentation/utils/dataset_utils.py
  person_image_segmentation/utils/modeling_utils.py
  person_image_segmentation/utils/processing.py
  person_image_segmentation/utils/run_kaggle_model.py
  poetry.lock
  tests/test_api.py
  tests/test_data.py
  tests/test_model.py
Labels: maintenance

#48 [FEAT] Model data cards update
  references/cards/DatasetCard.md
  references/cards/ModelCard.md
Labels: documentation

#50 [FIX] Kaggle environment variables
  person_image_segmentation/utils/run_kaggle_dataset.py
  person_image_segmentation/utils/run_kaggle_model.py
Labels: bug

#51 [FEAT] Api updates
  dvc.lock
  person_image_segmentation/api/app.py
  person_image_segmentation/utils/api_utils.py
  reports/coverage_pytest/class_index.html
  reports/coverage_pytest/function_index.html
  reports/coverage_pytest/index.html
  reports/coverage_pytest/status.json
  reports/coverage_pytest/z_0d0db7db8e6f5e5a_app_py.html
  reports/coverage_pytest/z_0d0db7db8e6f5e5a_schema_py.html
  reports/coverage_pytest/z_193685411ac05adf_api_utils_py.html
  reports/coverage_pytest/z_193685411ac05adf_dataset_utils_py.html
  reports/coverage_pytest/z_193685411ac05adf_modeling_utils_py.html
  reports/coverage_pytest/z_193685411ac05adf_processing_py.html
  reports/coverage_pytest/z_3acf147be2e23a47_config_py.html
  tests/test_api.py
Labels: enhancement

#49 [CHORE] Update readme
  README.md
  person_image_segmentation/pipelines/download_raw_data.py
  person_image_segmentation/pipelines/readme.md
Labels: documentation

#57 [CHORE] Remove unnecessary loadenv
  notebooks/0_NG_data-pipelines.ipynb
  notebooks/1_MJ_mlflow-experiments.ipynb
  notebooks/2_MR_predictions-and-postprocessing-pipeline.ipynb
  notebooks/3_MR_evaluation.ipynb
  person_image_segmentation/api/app.py
  person_image_segmentation/config.py
  person_image_segmentation/modeling/evaluation.py
  person_image_segmentation/modeling/prediction.py
  person_image_segmentation/pipelines/download_raw_data.py
  person_image_segmentation/pipelines/readme.md
  person_image_segmentation/utils/run_kaggle_dataset.py
  person_image_segmentation/utils/run_kaggle_model.py
  tests/deepchecks_validation.py
  tests/test_api.py
  tests/test_data.py
  tests/test_model.py
Labels: maintenance

#58 [FEAT] Solve errors in API for good error reporting
  person_image_segmentation/api/app.py
  person_image_segmentation/utils/api_utils.py
  tests/test_api.py
Labels: bug

#59 [FEAT] Update API files and README
  README.md
  frontend/README.md
  person_image_segmentation/api/app.py
  reports/coverage_pytest/class_index.html
  reports/coverage_pytest/function_index.html
  reports/coverage_pytest/index.html
  reports/coverage_pytest/status.json
  reports/coverage_pytest/z_0d0db7db8e6f5e5a_app_py.html
  reports/coverage_pytest/z_0d0db7db8e6f5e5a_schema_py.html
  reports/coverage_pytest/z_193685411ac05adf_api_utils_py.html
  reports/coverage_pytest/z_193685411ac05adf_dataset_utils_py.html
  reports/coverage_pytest/z_193685411ac05adf_modeling_utils_py.html
  reports/coverage_pytest/z_193685411ac05adf_processing_py.html
  reports/coverage_pytest/z_3acf147be2e23a47_config_py.html
  tests/test_api.py
Labels: documentation, enhancement
